# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6c2ad4b57502d3a0d342a73107a6a79fb0c81aae4992b7b4a7e86e46de3292ac73aa2a969e8ce07764f9698031f55216905e2ebbda56f1bae3df0ac5f3fb26a
  stripe_secret_key: sk_test_1mWgEVDu16Rdc8rHfgy8JnMG
  stripe_publishable_key: pk_test_rfe62QaA2ZGw7GyTvtWLREVk


test:
  secret_key_base: e7a9fc471b306cacf27672936e3902006a4362d6fde3bdeb2a017060a3b4bf0b02e1d2d8900b5ede30394317013c688889a87a948929e260ba46c8f22bd56fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: sk_live_WhCNPLD01SESuEeEVTPwzO5l
  stripe_publishable_key: pk_live_ct4sUZ8PlrZTBYz0dmmU8CY6
